## KNN

In [5]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [6]:
df = pd.read_csv('../../data/train_V2.csv')

In [7]:
df[:10]

,Unnamed: 0,OutcomeType,Cat,Dog,Female,Intact,Male,Neutered,Spayed,Age,...,Tan,Tick,Tiger,Torbie,Tortie,Tricolor,White,Yellow,Mixed,Purebred
0,0,Return_to_owner,0,1,0,0,1,1,0,365,...,0,0,0,0,0,0,1,0,1,0
1,1,Euthanasia,1,0,1,0,0,0,1,365,...,0,0,0,0,0,0,0,0,1,0
2,2,Adoption,0,1,0,0,1,1,0,730,...,0,0,0,0,0,0,1,0,1,0
3,3,Transfer,1,0,0,1,1,0,0,21,...,0,0,0,0,0,0,0,0,1,0
4,4,Transfer,0,1,0,0,1,1,0,730,...,1,0,0,0,0,0,0,0,0,1
5,5,Transfer,0,1,1,1,0,0,0,30,...,1,0,0,0,0,0,0,0,0,1
6,6,Transfer,1,0,0,1,1,0,0,21,...,0,0,0,0,0,0,0,0,1,0
7,7,Transfer,1,0,0,0,0,0,0,21,...,0,0,0,0,0,0,0,0,1,0
8,8,Adoption,0,1,1,0,0,0,1,150,...,0,0,0,0,0,0,1,0,1,0
9,9,Adoption,0,1,1,0,0,0,1,365,...,0,0,0,0,0,0,1,0,0,1

In [8]:
feature_cols = ['Cat','Dog','Female','Intact','Male','Neutered','Spayed','Age','Tan','Tick','Tiger','Torbie','Tricolor','White','Yellow','Mixed','Purebred']

X = df[feature_cols]

In [9]:
y = df['OutcomeType']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [11]:
k = 24
my_knn = KNeighborsClassifier(n_neighbors=k)
my_knn.fit(X_train, y_train)
y_predict = my_knn.predict(X_test)
accuracy = accuracy_score(y_test, y_predict)

print(accuracy)

0.6219603441825664

In [13]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')